/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-01-14

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include <stm32f0xx.h>

#include "i2c.h"
#include "vl53l0x_device.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/


//#define VL53L0x_add 0x52 //IIC device address of VL53L0x
#define MY_VL53L0x_add 0x29 //my

typedef uint8_t bool;
uint8_t stop_var;
uint8_t config_cntrl;

void VL53L0X_getSpadInfo(uint8_t* count, bool* type_is_aperture) {
//	uint8_t tmp;
//
//	VL53L0X_writeReg(0x80, 0x01);
//	VL53L0X_writeReg(0xFF, 0x01);
//	VL53L0X_writeReg(0x00, 0x00);
//
//	VL53L0X_writeReg(0xFF, 0x06);
//	VL53L0X_writeReg(0x83, VL53L0X_readReg(0x83) | 0x04);
//	VL53L0X_writeReg(0xFF, 0x07);
//	VL53L0X_writeReg(0x81, 0x01);
//
//	VL53L0X_writeReg(0x80, 0x01);
//
//	VL53L0X_writeReg(0x94, 0x6b);
//	VL53L0X_writeReg(0x83, 0x00);
//	startTimeout();
//	while (VL53L0X_readReg(0x83) == 0x00) {
//		if (checkTimeoutExpired()) {
//			return false;
//		}
//	}
//	VL53L0X_writeReg(0x83, 0x01);
//	tmp = VL53L0X_readReg(0x92);
//
//	*count = tmp & 0x7f;
//	*type_is_aperture = (tmp >> 7) & 0x01;
//
//	VL53L0X_writeReg(0x81, 0x00);
//	VL53L0X_writeReg(0xFF, 0x06);
//	VL53L0X_writeReg(0x83, VL53L0X_readReg(0x83 & ~0x04));
//	VL53L0X_writeReg(0xFF, 0x01);
//	VL53L0X_writeReg(0x00, 0x01);
//
//	VL53L0X_writeReg(0xFF, 0x00);
//	VL53L0X_writeReg(0x80, 0x00);
}

void vl53L0x_init() {
	i2c1_init();

	CLEAR_XSHUT();
	for (int i = 0; i < 10000; i++);
	SET_XSHUT();
	for (int i = 0; i < 10000; i++);
	i2c1_sendByte(MY_VL53L0x_add, VL53L0X_REG_IDENTIFICATION_MODEL_ID);
	uint8_t temp_data[8];
	i2c1_get(MY_VL53L0x_add, temp_data, 8);

	vl53L0x_writeReg(0x88, 0x00);
	vl53L0x_writeReg(0x80, 0x01);
	vl53L0x_writeReg(0xFF, 0x01);
	vl53L0x_writeReg(0x00, 0x00);

	vl53L0x_readReg(0x91, &stop_var, 1);

	vl53L0x_writeReg(0x00, 0x01);
	vl53L0x_writeReg(0xFF, 0x00);
	vl53L0x_writeReg(0x80, 0x00);

	vl53L0x_readReg(VL53L0X_REG_MSRC_CONFIG_CONTROL, &config_cntrl, 1);
	vl53L0x_writeReg(VL53L0X_REG_MSRC_CONFIG_CONTROL, config_cntrl | 0x12);
	vl53L0x_writeReg(VL53L0X_REG_FINAL_RANGE_CONFIG_MIN_COUNT_RATE_RTN_LIMIT, (uint16_t)(0.25 * (1 << 7)));/*0.25ms*/
	vl53L0x_writeReg(VL53L0X_REG_SYSTEM_SEQUENCE_CONFIG, 0xFF);

	uint8_t spad_count;
	bool spad_type_is_aperture;
	VL53L0X_getSpadInfo(&spad_count, &spad_type_is_aperture);


}
void vl53L0x_writeReg(uint8_t reg, uint8_t data) {
	uint8_t temp_data[2] = {reg, data};
	i2c1_send_str(MY_VL53L0x_add, temp_data, 2);
}

void vl53L0x_readReg(uint8_t reg, uint8_t *data, uint8_t size) {
	i2c1_sendByte(MY_VL53L0x_add, reg);
	i2c1_get(MY_VL53L0x_add, data, size);
}

uint8_t data_range[14];
void vl53L0x_startMeas() {

}




int main(void)
{
	uint8_t temp_data[4];
	vl53L0x_init();

//	i2c1_sendByte(VL53L0x_add, VL53L0X_REG_SYSRANGE_START);
//
//
//	i2c1_sendByte(VL53L0x_add, VL53L0X_REG_RESULT_RANGE_STATUS);
//	i2c1_get(VL53L0x_add, temp_data, 4);

	vl53L0x_startMeas();

	while(1) {
//		for (int i = 0; i < 100000; i++);
//		vl53L0x_startMeas();
	}

}
